### ISSUE TITLE
Door of Time Not Opening

### ISSUE THREAD

**Issue by engineerdave16** [gamestabled/OoT3D_Randomizer#372]
All three Spiritual Stones appear in front of the pedestal, I play the Song of Time, the cutscene happens with the triforce lighting up, but the Door of Time does not open

edit: It's v1.0.2_056c32 and the Door of Time setting is set to Open

**Comment by gamestabled** [comment]
Since the door was closed, but you had the setting on Open, it seems likely that your save file was created without the randomizer active, which probably caused the issue. This also happened on an old version and we haven't heard more about something like this since, so it seems unlikely that this is still an issue.
