### ISSUE TITLE
Invalid Way of the Hero hint?

### ISSUE THREAD

**Issue by vrwntrs** [gamestabled/OoT3D_Randomizer#495]
V3.1-58708c
Seed: 2035233746

I received a hint that Goron City was Way of the Hero. However, the only items I could possibly see to be WotH there were Cojiro (traded for a Heart Piece, but Odd Poultice did trade for magic meter) and a buyable Goron Tunic. 

As far as I can tell from the spoiler log, I could have gotten a different magic or tunic.

As I understand it from the OOT Randomizer wiki, an item with multiple instances like tunics and magic will not be Way of the Hero unless the other instances are locked behind it (like if the second magic meter was in Shadow Temple).

Did I misunderstand the way hints work? Or is there something I missed with the logic? Or did something go wrong with the hint?

[Spoiler log here](https://drive.google.com/file/d/1SsmLou0KylLzfKVkLCp7crtx37L_aSFm/view?usp=drivesdk)

**Comment by gymnast86** [comment]
Cojiro is the Way of the Hero item in Goron City. Due to the way that Spirit Temple logic is handled, getting the progressive magic in Spirit Temple required getting 4 Spirit Temple keys. But the key in the sun block room chest can only be logically collected without magic if all 5 small keys can be collected beforehand. So in this case logic required needing magic for either Din's Fire or Fire Arrows before being able to reach the 2nd progressive magic.
