### ISSUE TITLE
0-0 insta kill with ISG 

### ISSUE THREAD

**Issue by Imperfectplay** [gamestabled/OoT3D_Randomizer#584]
I have run into quite an interesting bug with the restored ISG. (For reference I am playing on V3.1-b0c7c3) After obtaining ISG start walking with your weapon drawn then press X or Y with either, bow/slingshot/hookshot/boomerang to force link to put his weapon away, this will cause every enemy killable with zero-zero coordinates. I have tested this on several maps in-game as child and adult with all weapons mentioned. Most notably are places with alot of guays, as those will spawn in rather quickly when there's none left on the map resulting in serious lag, worst being lake hylia.

I have not been able to find out if this always happens in vanilla oot3d when you have ISG or if it's just with restored ISG in rando.

**Comment by HylianFreddy** [comment]
This happens in the vanilla game too.

It works because in OoT3D, to make it easier to hit stuff with the sword, they added spherical colliders to the sword's hitbox. If the sword is put away, those colliders don't exist, so when the game checks to see if they're hitting other spherical colliders it always returns true, due to a calculation error. So every enemy or object with spherical colliders will be hit on every frame.

You can use it as a cool exploit to kill skulltulas or hit distant switches, but remember that if you do ISG with a sign or NPC you should wait for the enemy's death flash to finish before closing the textbox (otherwise you might softlock the game if you close it while the flash is happening).

**Comment by Imperfectplay** [comment]
HylianFreddy thanks so much for letting me know that this is a vanilla oot3d glitch. I appreciate your detailed response, thanks for letting me know about the soft lock issue!
