### ISSUE TITLE
Desert Colossus music glitches out once you reach the Silver Gauntlets or Mirror Shield chest

### ISSUE THREAD

**Issue by 03bgood** [gamestabled/OoT3D_Randomizer#87]
The music stops playing even if you exit the Spirit Temple or warp using Requiem of Spirit. This is a minor bug but it needs to be fixed. AFAIK, this never happened in the original N64 rando.

**Comment by gamestabled** [comment]
It's believable that something like this occurred involving the spirit temple entrances either with the randomizer affecting the requiem of spirit cutscene or just in oot3d in general. but nobody has said something like this since this post and we dont know what it could be. so gonna close it and it can be looked into if it comes back up
